logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG

mail:
    mygarden: "mygarden@example.com"
    host: localhost
    port: 1025
    username: ${MAIL_USER:mygarden}
    password: ${MAIL_PASSWORD:mygarden}

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/my_garden?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    sql:
        init:
            mode: never
    mvc:
        hiddenmethod:
            filter:
                enabled: true
