cloudinary:
    api-key: 487839896536817
    api-secret: ${CLOUD_API_SECRET}
    cloud-name: ds4tkr2vb
logging:
    level:
        blog: WARN
        org: WARN
#        org.hibernate.SQL: DEBUG
mail:
    host: localhost
    mygarden: mygarden@example.com
    password: ${MAIL_PASSWORD:mygarden}
    port: 1025
    username: ${MAIL_USER:mygarden}
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/my_garden?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
    sql:
        init:
            mode: never
